name: ui_state_machine
description: Describes views and transitions of an app in a state machine like manor.
version: 1.0.0
homepage: https://github.com/ozML/ui_state_machine

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter